// ============================================================
// 記事データ
// URLは実際のリベシティの記事URLに書き換えてください
// level: 1=初心者 2=実践中 3=成長期 4=拡大期
// content_type: story=体験談 howto=手順解説 lesson=失敗教訓 data=数字・分析
// target_problems: start=何から始めるか earn=稼げない time=時間がない stable=収入不安定
// ============================================================
const ARTICLES_DATA = [
  {
    id: "art_001",
    title: "副業ゼロから月3万円稼ぐまでにやったこと全部",
    summary: "SNS発信もゼロ、スキルもゼロから3ヶ月で副業収入を得るまでの具体的な行動記録。失敗談も全部公開。",
    url: "#",
    category: "副業収入",
    tags: ["初月収", "行動記録", "副業入門"],
    level: 1,
    read_minutes: 5,
    updated_at: "2025-03-15",
    likes: 245,
    bookmarks: 89,
    target_problems: ["start", "earn"],
    content_type: "story"
  },
  {
    id: "art_002",
    title: "SNS発信を始める前に絶対知っておきたい3つのこと",
    summary: "始める前の準備不足で3ヶ月無駄にした経験から学んだ、発信前チェックリスト。初心者向け。",
    url: "#",
    category: "SNS発信",
    tags: ["SNS入門", "発信準備", "初心者"],
    level: 1,
    read_minutes: 4,
    updated_at: "2025-04-01",
    likes: 312,
    bookmarks: 134,
    target_problems: ["start"],
    content_type: "howto"
  },
  {
    id: "art_003",
    title: "情報収集を半分に減らしたら収入が2倍になった話",
    summary: "「インプット中毒」から抜け出したら人生が変わった。情報過多の現代に必要なインプット断食のすすめ。",
    url: "#",
    category: "マインド",
    tags: ["情報断食", "行動力", "インプット"],
    level: 1,
    read_minutes: 6,
    updated_at: "2025-02-20",
    likes: 421,
    bookmarks: 156,
    target_problems: ["start", "earn"],
    content_type: "story"
  },
  {
    id: "art_004",
    title: "Twitterフォロワー100人の壁を超えた具体的な方法",
    summary: "0→100人に3ヶ月かかった私が1週間で突破できた方法。投稿内容・時間帯・返信戦略を全公開。",
    url: "#",
    category: "SNS発信",
    tags: ["Twitter", "フォロワー", "SNS攻略"],
    level: 2,
    read_minutes: 7,
    updated_at: "2025-03-28",
    likes: 189,
    bookmarks: 78,
    target_problems: ["earn"],
    content_type: "howto"
  },
  {
    id: "art_005",
    title: "初めて商品を5万円で売れた日の話",
    summary: "「自分の商品なんて誰も買わない」という思い込みが崩れた瞬間。初売上を得るまでの心理変化。",
    url: "#",
    category: "マネタイズ",
    tags: ["初売上", "商品設計", "マインド"],
    level: 2,
    read_minutes: 5,
    updated_at: "2025-04-10",
    likes: 356,
    bookmarks: 112,
    target_problems: ["earn"],
    content_type: "story"
  },
  {
    id: "art_006",
    title: "月10万円達成までに私がやったこと全部リスト",
    summary: "副業開始から8ヶ月で月10万円を達成。やったこと・やらなくてよかったことを全部書いた記録。",
    url: "#",
    category: "副業収入",
    tags: ["月10万", "実績公開", "ロードマップ"],
    level: 2,
    read_minutes: 9,
    updated_at: "2025-01-15",
    likes: 567,
    bookmarks: 234,
    target_problems: ["earn", "start"],
    content_type: "story"
  },
  {
    id: "art_007",
    title: "コンテンツ販売で月5万円の仕組みを作った方法",
    summary: "一度作れば売れ続ける仕組みの具体的な作り方。プラットフォーム選び・価格設定・集客まで。",
    url: "#",
    category: "マネタイズ",
    tags: ["コンテンツ販売", "仕組み化", "月5万"],
    level: 2,
    read_minutes: 8,
    updated_at: "2025-03-05",
    likes: 298,
    bookmarks: 143,
    target_problems: ["earn", "time"],
    content_type: "howto"
  },
  {
    id: "art_008",
    title: "保存される投稿を量産するための5つの型",
    summary: "フォロワー数よりも保存数が大事な理由と、保存されやすい投稿の型を実例付きで解説。",
    url: "#",
    category: "SNS発信",
    tags: ["保存率", "投稿の型", "SNS攻略"],
    level: 2,
    read_minutes: 6,
    updated_at: "2025-04-20",
    likes: 445,
    bookmarks: 198,
    target_problems: ["earn"],
    content_type: "howto"
  },
  {
    id: "art_009",
    title: "値上げしたら売上が1.5倍になった理由",
    summary: "怖くて値上げできなかった私が値上げを決断した経緯と、実際に起きた変化の記録。",
    url: "#",
    category: "マネタイズ",
    tags: ["値上げ", "価格設定", "自己価値"],
    level: 3,
    read_minutes: 5,
    updated_at: "2025-02-10",
    likes: 389,
    bookmarks: 167,
    target_problems: ["time", "stable"],
    content_type: "story"
  },
  {
    id: "art_010",
    title: "外注化で週20時間を取り戻した話",
    summary: "全部1人でやろうとしていた私が外注化に踏み切るまで。最初の1人目をどう探したかも公開。",
    url: "#",
    category: "組織化",
    tags: ["外注化", "時間管理", "チーム"],
    level: 3,
    read_minutes: 7,
    updated_at: "2025-03-20",
    likes: 312,
    bookmarks: 145,
    target_problems: ["time"],
    content_type: "story"
  },
  {
    id: "art_011",
    title: "リピーター率80%を達成した顧客対応の仕組み",
    summary: "新規集客より既存顧客を大切にしたら売上が安定した。具体的な仕組みとツールを公開。",
    url: "#",
    category: "マネタイズ",
    tags: ["リピーター", "顧客管理", "安定収入"],
    level: 3,
    read_minutes: 8,
    updated_at: "2025-01-30",
    likes: 276,
    bookmarks: 123,
    target_problems: ["stable", "time"],
    content_type: "howto"
  },
  {
    id: "art_012",
    title: "フォロワー1000人超えてから変わった3つのこと",
    summary: "1000人という節目で見えてきた景色と、次のステージで必要になるマインドチェンジについて。",
    url: "#",
    category: "SNS発信",
    tags: ["1000人", "SNS成長", "マインドチェンジ"],
    level: 3,
    read_minutes: 5,
    updated_at: "2025-04-05",
    likes: 334,
    bookmarks: 89,
    target_problems: ["stable", "time"],
    content_type: "story"
  },
  {
    id: "art_013",
    title: "本業を辞めた日に感じたこととやるべきこと",
    summary: "独立した日の正直な感情記録。準備しておけばよかったこと・しなくてよかった心配をまとめた。",
    url: "#",
    category: "マインド",
    tags: ["独立", "転機", "体験談"],
    level: 3,
    read_minutes: 6,
    updated_at: "2025-02-28",
    likes: 512,
    bookmarks: 201,
    target_problems: ["stable"],
    content_type: "story"
  },
  {
    id: "art_014",
    title: "月30万円を安定させるまでにやったこと",
    summary: "単発の高収入から安定した月収へ。収入の波をなくすために取り組んだ具体的な施策。",
    url: "#",
    category: "副業収入",
    tags: ["月30万", "安定収入", "独立"],
    level: 4,
    read_minutes: 10,
    updated_at: "2025-03-10",
    likes: 478,
    bookmarks: 212,
    target_problems: ["stable"],
    content_type: "story"
  },
  {
    id: "art_015",
    title: "チームを作って売上を2倍にした具体的な方法",
    summary: "1人から3人チームへ。メンバーの採用・育成・報酬設計まで全部公開した組織化記録。",
    url: "#",
    category: "組織化",
    tags: ["チーム", "採用", "スケール"],
    level: 4,
    read_minutes: 12,
    updated_at: "2025-01-20",
    likes: 289,
    bookmarks: 134,
    target_problems: ["time", "stable"],
    content_type: "howto"
  },
  {
    id: "art_016",
    title: "価格設定を3倍にして利益率が劇的に上がった話",
    summary: "安売りをやめた決断と、高単価でも売れる商品設計・ポジショニングの考え方。",
    url: "#",
    category: "マネタイズ",
    tags: ["高単価", "価格設定", "利益率"],
    level: 4,
    read_minutes: 8,
    updated_at: "2025-04-15",
    likes: 367,
    bookmarks: 178,
    target_problems: ["stable", "time"],
    content_type: "data"
  },
  {
    id: "art_017",
    title: "初心者が最初の1件を受注するまでのステップ",
    summary: "実績ゼロから最初のクライアントを得る方法。プロフィール設計・提案文・価格設定を全部解説。",
    url: "#",
    category: "副業収入",
    tags: ["初受注", "クライアント", "副業入門"],
    level: 1,
    read_minutes: 7,
    updated_at: "2025-04-25",
    likes: 389,
    bookmarks: 167,
    target_problems: ["start"],
    content_type: "howto"
  },
  {
    id: "art_018",
    title: "自分の強みを見つけてマネタイズした話",
    summary: "「特別なスキルがない」と思っていた私が強みを発見し、収入につなげるまでの思考プロセス。",
    url: "#",
    category: "マネタイズ",
    tags: ["強み発見", "自己分析", "初心者"],
    level: 1,
    read_minutes: 6,
    updated_at: "2025-03-01",
    likes: 445,
    bookmarks: 189,
    target_problems: ["start", "earn"],
    content_type: "story"
  },
  {
    id: "art_019",
    title: "SNSゼロからコンサル月収を得るまでの3ヶ月",
    summary: "フォロワー0から始めてコンサルティング収入を得るまで。何をどの順番でやったかを時系列で公開。",
    url: "#",
    category: "SNS発信",
    tags: ["コンサル", "SNS集客", "3ヶ月"],
    level: 2,
    read_minutes: 9,
    updated_at: "2025-02-15",
    likes: 512,
    bookmarks: 223,
    target_problems: ["earn", "start"],
    content_type: "story"
  },
  {
    id: "art_020",
    title: "行動できない本当の理由と今日から変える方法",
    summary: "「わかってるけど動けない」の正体とその対処法。脳科学・心理学の観点から実践的な解決策を提案。",
    url: "#",
    category: "マインド",
    tags: ["行動力", "先延ばし", "マインドセット"],
    level: 1,
    read_minutes: 5,
    updated_at: "2025-04-08",
    likes: 634,
    bookmarks: 278,
    target_problems: ["start"],
    content_type: "howto"
  },
  {
    id: "art_021",
    title: "SNS発信で「この人から買いたい」と思われる方法",
    summary: "フォロワー数よりも信頼構築が先。初心者が最初にやるべきポジショニングの作り方。",
    url: "#",
    category: "SNS発信",
    tags: ["信頼構築", "ポジショニング", "集客"],
    level: 1,
    read_minutes: 5,
    updated_at: "2025-04-18",
    likes: 298,
    bookmarks: 121,
    target_problems: ["start", "earn"],
    content_type: "howto"
  },
  {
    id: "art_022",
    title: "失敗から学んだ副業を辞めそうになった3つの瞬間",
    summary: "3回やめかけた経験と、そのたびに乗り越えたマインドの変え方。継続できた理由を正直に話す。",
    url: "#",
    category: "マインド",
    tags: ["継続力", "失敗談", "挫折"],
    level: 2,
    read_minutes: 6,
    updated_at: "2025-03-22",
    likes: 467,
    bookmarks: 198,
    target_problems: ["earn"],
    content_type: "lesson"
  },
  {
    id: "art_023",
    title: "数字で見る：保存される記事と流し見される記事の違い",
    summary: "100記事分析してわかった「保存されるコンテンツ」の共通点。データで解説。",
    url: "#",
    category: "SNS発信",
    tags: ["データ分析", "コンテンツ戦略", "保存率"],
    level: 3,
    read_minutes: 8,
    updated_at: "2025-04-12",
    likes: 234,
    bookmarks: 167,
    target_problems: ["stable", "earn"],
    content_type: "data"
  }
];
